[build]
  command = "npm --prefix southtownslandservice ci && npm --prefix southtownslandservice run build"
  publish = "southtownslandservice/dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200